/********************************************************************
 *                    COPYRIGHT PARROT 2010
 ********************************************************************
 *       PARROT - A.R.Drone SDK Windows Client Example
 *-----------------------------------------------------------------*/

/*
Warning !!!!
This file is normally automatically generated by the A.R. Drone SDK Makefile.
This is a local copy manually modified for use with the Windows client demonstration.

Parameters concerning network configuration (IP adress, Wifi SSID ...)
are not used, since we let Windows handle this.

Parameters concerning the video resolution must be set accordingly to the parameters
used to compile the drone software (here are the default which were certainly used
for the public-released drones.
*/

#ifndef _GENERATED_CUSTOM_CONFIGURATION_H_
#define _GENERATED_CUSTOM_CONFIGURATION_H_



#endif // ! _GENERATED_CUSTOM_CONFIGURATION_H_
